name: deploy
on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: [self-hosted, private]
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Deploy as Docker Container
        run: docker compose up -d --build
        env:
          COMPOSE_PROFILES: production
          TOKEN: ${{ secrets.TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Display Logs
        run: python3 -m exendlr bobux-admin "bot is ready"

      - name: Remove Unused Containers
        run: docker image prune -f
